version: "3.9"

services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secretpassword
      MYSQL_ROOT_PASSWORD: secretpassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    container_name: app
    build: .
    command: go run main.go
    volumes:
      - .:/code/
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: app
      DB_USER: appuser
      DB_PASSWORD: secretpassword
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
